name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Brew
      run: brew update && brew bundle
    - name: Bundle
      run: bundle install
    - name: Fastlane
      run: bundle exec fastlane ci
